import assert from 'node:assert/strict';
import { STORAGE_KEY, examples, readSnippets, saveSnippet, deleteSnippet } from './store.js';
const data = new Map();
const storage = { getItem: key => data.get(key) ?? null, setItem: (key, value) => data.set(key, value) };
assert.equal(readSnippets(storage).length, examples.length);
assert.ok(saveSnippet(storage, { title: '', content: '', visibility: 1 }).errors.title);
const created = saveSnippet(storage, { title: 'Test snippet', content: 'console.log(1)', CodingLanguage: '', visibility: 2 });
assert.equal(created.snippet.CodingLanguage, 'Text');
assert.equal(readSnippets(storage).length, examples.length + 1);
const updated = saveSnippet(storage, { title: 'Updated', content: 'console.log(2)', CodingLanguage: 'JavaScript' }, created.snippet.slug);
assert.equal(updated.snippet.visibility, 2);
assert.equal(updated.snippet.content, 'console.log(2)');
assert.equal(readSnippets(storage).find(s => s.slug === created.snippet.slug).title, 'Updated');
deleteSnippet(storage, created.snippet.slug);
assert.equal(readSnippets(storage).length, examples.length);
for (const s of readSnippets(storage)) deleteSnippet(storage, s.slug);
assert.deepEqual(readSnippets(storage), []);
assert.throws(() => saveSnippet(storage, { title: 'Missing' }, 'missing'), /not found/);
storage.setItem(STORAGE_KEY, '{broken');
assert.throws(() => readSnippets(storage));
const blocked = { getItem: () => null, setItem: () => { throw new Error('Quota exceeded'); } };
assert.throws(() => saveSnippet(blocked, { title: 'Unsaved', content: 'code', visibility: 1 }), /Quota/);
console.log('Passed: create, validation, persistence, edit, visibility, delete, empty store, missing snippet, corrupt storage, storage failure.');
